# Generated by Django 5.0.14 on 2025-06-01 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
